### ISSUE TITLE
Improper rendering of money type

### ISSUE THREAD

**Issue by bwiggs** [psequel/psequel#100]
I can't seem to get psequel to render the `money` type correctly.

Here's the expected correct result from psql:

```
# psql (9.5.1, server 9.4.5)
postgres=# SELECT '12.34'::numeric::money;
 money
--------
 $12.34
(1 row)
```

In PSequel 1.4.2 I just get `0`.

![screenshot 2016-02-22 16 19 00](https://cloud.githubusercontent.com/assets/7358/13234814/338c9d7a-d980-11e5-92b6-5c96916c9e18.png)

**Comment by psequel** [comment]
Fixed in v1.4.3.
