### ISSUE TITLE
Query wrapping early instead of using full window width available

### ISSUE THREAD

**Issue by jayshepherd** [psequel/psequel#101]
With longer lines, it appears that it is wrapping too early instead of using all of the text space available.

Example steps to recreate:
```
SELECT * FROM table1 t1 JOIN table2 t2 ON t1.id = t2.id WHERE t1.name = 'ASDF' AND t2.description ILIKE '%crocodiles%' AND t1.id > 3000 ORDER BY t1.description, t2.created_at
```

Paste that in a query window and notice where it wraps relative to the edge of the window:

![d72im75o0a5uol 2016-02-24 13-48-26](https://cloud.githubusercontent.com/assets/4238/13298742/af3a0cea-dafd-11e5-83c4-4e08290ccfac.png)

**Comment by psequel** [comment]
Fixed in v1.4.3.
