### ISSUE TITLE
1.4.2 unsigned

### ISSUE THREAD

**Issue by rdp** [psequel/psequel#102]
As a note, with 1.4.2 I get a security failure trying to open it:

"PSequel" can't be opened because the identity of the developer cannot be confirmed. (which is not a show stopper, but slows down opening it the first time).  1.4.0 seems to not have had this. Cheers!

**Comment by psequel** [comment]
Do you still see this issue for v1.4.3?

**Comment by nyaaao** [comment]
I've seen this on 1.4.3 as well, but that might be due to me being on the latest public beta (10.11.4 Beta (15E49a)). The `check-signature` tool says it should pass the check, though.

**Comment by rdp** [comment]
1.4.3 appears the same, this message:

“PSequel” can’t be opened because the identity of the developer cannot be confirmed. your security preferences allow installation of only apps from the Mac App Store and identified developers.

**Comment by psequel** [comment]
I paid $108 each year to become an "identified developer". Sounds like a bug of OS 10.11.4 beta. Anyway, I'll get this fixed once OS 10.11.4 is out of beta. Thanks for the follow-up.

**Comment by rdp** [comment]
FWIW, my OS is 10.10.5 in my particular case.

**Comment by rocketpastsix** [comment]
@rdp ctrl+click on the app and select open from the options. The first time you open the app you will have to do that, afterwards you can open like normal.

**Comment by psequel** [comment]
Do you still see this issue for v1.4.4?

**Comment by rdp** [comment]
Yes appears to be the same issue with 1.4.4

**Comment by psequel** [comment]
What about v1.5.0?

**Comment by rdp** [comment]
Seems to be working now, thanks!
