### ISSUE TITLE
wrong number of rows reported for alter table

### ISSUE THREAD

**Issue by rdp** [psequel/psequel#103]
run this:

ALTER TABLE tableName ADD zipFileName34 VARCHAR(256);

watch it say that "140000368777 rows updated" (or something, at least it did for me, 9.4.4)

**Comment by psequel** [comment]
You added a column to a table that contains 140000368777 rows, right?

**Comment by rdp** [comment]
In this instance the table has no rows.  I inserted one row and ran a similar query, and it returned me a similar "huge" number (like 140602915463936 [140 trillion]).  Interestingly, f I put in a "non query" in the query tab's pane, and hit "Run Query" , ex:

--;

It also reports those huge numbers.  HTH.  Dropping a column same thing.

**Comment by psequel** [comment]
Which version of PSequel are you using? I'm unable to reproduce this bug with PSequel v1.4.2. Could you please make sure you include the PSequel version when reporting a bug in future?

**Comment by rdp** [comment]
OK 1.4.2 and 1.4.2
Will do.
-roger-

**Comment by psequel** [comment]
Fixed in v1.5.1.
