### ISSUE TITLE
Support conventional CSV quote escaping

### ISSUE THREAD

**Issue by mgood** [psequel/psequel#108]
Thanks, I really like using PSequel, but I have to manually correct the copied CSV before importing into other tools to fix the quote escaping.

While there are a lot of different dialects of CSV, most tools seem to use two double quotes as an escaped double-quote character, as described in [the CSV RFC](https://www.ietf.org/rfc/rfc4180.txt).

```
   7.  If double-quotes are used to enclose fields, then a double-quote
       appearing inside a field must be escaped by preceding it with
       another double quote.  For example:

       "aaa","b""bb","ccc"
```

The two double-quotes is recognized by both Excel and Numbers, and is the default in the programming libraries I've used as well.

PSequel uses backslashes to escape double-quotes in values, which I've seen occasionally, but it doesn't seem to be as widely supported.

Would you consider switching to the two double-quotes for escaping, or provide a setting to switch CSV dialects if some users need to support a different format?

For example to reproduce:

Run query:
```sql
SELECT 'a " b' AS foo;
```

Copy as CSV

Pasted result is:
```
"foo"
"a \" b"
```

Instead, I would expect the quote to be escaped like:

```
"foo"
"a "" b"
```

**Comment by psequel** [comment]
Fixed in v1.5.0.
