### ISSUE TITLE
Export / Import Database Settings

### ISSUE THREAD

**Issue by reggi** [psequel/psequel#113]
I'm looking for a way to copy all of my different db settings and send it to another person and allow them to import.

**Comment by psequel** [comment]
You may try copying `~/Library/Application Support/com.psequel.PSequel/` which contains all your settings, not just connection settings.

**Comment by reggi** [comment]
@psequel I'm looking for a way to share connection settings with a coworker without copying and pasting everything. If I want to share dozens of connections there has to be an easy way.

**Comment by psequel** [comment]
PSequel may support this feature in future. For the time being, if you don't mind sharing more than you need, you could just share your entire `~/Library/Application Support/com.psequel.PSequel/` folder with your coworker.

**Comment by rdp** [comment]
The sharing did work for me (sans passwords of course), may as well leave this ticket open as a feature request :)
