### ISSUE TITLE
Feature Request: Export database to sql file

### ISSUE THREAD

**Issue by Fyb3roptik** [psequel/psequel#126]
Would love the option to just export all tables to a sql file. Thanks!

**Comment by psequel** [comment]
Currently PSequel focuses on making it easy to do repetitive tasks, which mean table viewing and editing. It's not trying to replace pgAdmin 3. Instead, it's designed to be supplementary to pgAdmin 3. For exporting the entire database to a file, which most users don't need to do very often, I'd suggest you to use pgAdmin 3. This feature might be implemented in PSequel in distant future.

**Comment by lsei** [comment]
+1
This is one of the features I love about Sequel Pro. It makes it really easy to import and export data from databases. Sometimes I want to quickly get a remote dataset and load it into a local db for testing and having to go through various steps to get the data and then reimport it can be a bit tedious. Anything to make this easier would be nice.

**Comment by Fyb3roptik** [comment]
I ended up buying Postico. It is way better than PSequel. I hope PSequel finally does get this feature going

**Comment by selfagency** [comment]
+1 would love import/export.

**Comment by Fyb3roptik** [comment]
I have turned to using Postico now. It is greatness and I recommend

**Comment by modelesque** [comment]
+1 can't believe this isn't in here.  Need to push my local Craft 3 database for my team up on staging..

**Comment by Fyb3roptik** [comment]
Just use Postico

**Comment by psequel** [comment]
As I stated earlier, PSequel focuses on making it easy to do repetitive tasks, which mean table viewing and editing. Exporting a database is just an easy `pg_dump` command and a GUI won't make this task simpler.

**Comment by dancork** [comment]
> As I stated earlier, PSequel focuses on making it easy to do repetitive tasks, which mean table viewing and editing. Exporting a database is just an easy pg_dump command and a GUI won't make this task simpler.

Think there are many that would disagree with this, for whom import/export is a repetitive task and a GUI would definitely make it simpler than using the command line.

**Comment by tomsoir** [comment]
PSequel dead. https://tableplus.io/blog/2018/07/psequel-is-dead-alternative-postgresql-gui-client-mac.html
