### ISSUE TITLE
Host key verification error with vagrant

### ISSUE THREAD

**Issue by ChristianVermeulen** [psequel/psequel#128]
Everything was working fine until I switched to another vagrant box (I have multiple because I work on multiple projects). So I suspended the current box, and up'ed the other box. Next I changed the DB credentials and vagrant private key to meet the other box and I get a host key verification error.

At first it was a warning and I got an offending line in my known_hosts, but after removing that line it just can't verify anymore. On either box.... I've updated Vagrant (1.8.5), Virtual Box (5.0.26) and PSequel (1.5.0). I also tried destroying and recreating the vagrant boxes with the hopes of a new set of keys but to no avail...

```
OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data /Users/seer/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: /etc/ssh/ssh_config line 56: Applying options for *
debug1: Connecting to localhost [::1] port 2222.
debug1: connect to address ::1 port 2222: Connection refused
debug1: Connecting to localhost [127.0.0.1] port 2222.
debug1: fd 5 clearing O_NONBLOCK
debug1: Connection established.
debug1: key_load_public: No such file or directory
debug1: identity file /path/to/project/.vagrant/machines/default/virtualbox/private_key type -1
debug1: key_load_public: No such file or directory
debug1: identity file /path/to/project/.vagrant/machines/default/virtualbox/private_key-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.9
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.7
debug1: match: OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.7 pat OpenSSH_6.6.1* compat 0x04000000
debug1: Authenticating to localhost:2222 as 'vagrant'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client chacha20-poly1305@openssh.com <implicit> none
debug1: kex: client->server chacha20-poly1305@openssh.com <implicit> none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:8/Fu88iIZemFSiQwTZ3uK/jBzLX3mYMkW4HalHtPPlI
debug1: checking without port identifier
debug1: read_passphrase: can't open /dev/tty: Device not configured
debug1: permanently_drop_suid: 502
ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory
Host key verification failed.
```

These are my settings:
<img width="872" alt="screenshot 2016-08-12 11 42 12" src="https://cloud.githubusercontent.com/assets/1062751/17618772/e0b90dc0-6081-11e6-80a0-bee02dd97b35.png">

And I verified that my vagrant uses 2222 for ssh and I have forwarded port 5432 as well.

```
Host default
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /path/to/project/.vagrant/machines/default/virtualbox/private_key
  IdentitiesOnly yes
  LogLevel FATAL
```

```
# In Vagrantfile
config.vm.network "forwarded_port", guest: 5432, host: 5432
```

I already found several other issues here and a few topics through Google, but none have been helpful so far :(. I'm quite out of resources at this point! Hopefully you guys can figure this out?

Solutions tried until now:
- Tried using personal insecure_private_key in ~/.vagrant
- Tried using privat_key in /path/to/project/.vagrant
- Destroy  / Up the vagrant box
- Cut / Paste the private kay path (bug which wouldn't read the field if not changed)
- Removed offending (localhost) line from `know_hosts` on host machine
- Removed `known_hosts` from vagrant machine
- Updating to last stable versions (Vagrant, Virtual Box, PSequel, vagrant Box - trusty64)

p.s.: Working on Mac 10.11.6 (El Capitan)

**Comment by psequel** [comment]
> debug1: identity file /path/to/project/.vagrant/machines/default/virtualbox/private_key type -1
> debug1: key_load_public: No such file or directory

Looks like `/path/to/project/.vagrant/machines/default/virtualbox/private_key` doesn't exist?

BTW, since you already have port forwarding setup in your Vagrantfile, why do you need to set it up again in PSequel?

**Comment by ChristianVermeulen** [comment]
I double checked, the file definitely exists, i even tried copy pasting it from `vagrant ssh-config` to be sure. Might it be a permissions issue?

Portforwarding was a second try, but that also means a lot of configuration on the vagrant box to make it listen which I couldn't get to work either. I prefer using the SSH tunnel, which I always have been using.

**Comment by ChristianVermeulen** [comment]
So I just tried setting different rights on both the account wide insecure_private_key and the box specific private_key. Even tried 777, but it still says `no such file or directory`.

Any other ideas?

**Comment by ChristianVermeulen** [comment]
So, just to confirm, I just tried logging in with a different app (Valentina Studio) and it works like a charm, so the problem is definitely with Psequel! If you need me to do any other debugging let me know.

**Comment by psequel** [comment]
Wait, why the hostname/IP of your vagrant box (the "SSH Host" field) is "localhost"? Shouldn't be 192.168.*.* usually?

**Comment by jrods** [comment]
I'm also having the same issue.
@psequel by default, vagrant will use NAT for networking, so connecting to the vm will use the localhost/loopback ip address

**Comment by psequel** [comment]
@ChristianVermeulen According to your screenshot, PSequel is using this command to set up port forwarding:

`/usr/bin/ssh vagrant@localhost -vNL 5432:localhost:5432 -p 2222 -i /path/to/project/.vagrant/machines/default/virtualbox/private_key -o ExitOnForwardFailure=yes -o ConnectTimeout=30 -o TCPKeepAlive=no -o ServerAliveInterval=60`

Could you try this command in terminal? If it prints the same error, could you try replacing either/both 'localhost' with 127.0.0.1?

**Comment by ChristianVermeulen** [comment]
@psequel When I run it in terminal it seems to work perfectly....

```
$ /usr/bin/ssh vagrant@localhost -vNL 5432:localhost:5432 -p 2222 -i .vagrant/machines/default/virtualbox/private_key -o ExitOnForwardFailure=yes -o ConnectTimeout=30 -o TCPKeepAlive=no -o ServerAliveInterval=60
OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data /Users/*****/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: /etc/ssh/ssh_config line 56: Applying options for *
debug1: Connecting to localhost [::1] port 2222.
debug1: connect to address ::1 port 2222: Connection refused
debug1: Connecting to localhost [127.0.0.1] port 2222.
debug1: fd 5 clearing O_NONBLOCK
debug1: Connection established.
debug1: key_load_public: No such file or directory
debug1: identity file .vagrant/machines/default/virtualbox/private_key type -1
debug1: key_load_public: No such file or directory
debug1: identity file .vagrant/machines/default/virtualbox/private_key-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.9
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.7
debug1: match: OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.7 pat OpenSSH_6.6.1* compat 0x04000000
debug1: Authenticating to localhost:2222 as 'vagrant'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client chacha20-poly1305@openssh.com <implicit> none
debug1: kex: client->server chacha20-poly1305@openssh.com <implicit> none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:eo5vr5qNRTMBExXiijYoqIcdtrLtpeAD7hyWZlR+4cw
debug1: Host '[localhost]:2222' is known and matches the ECDSA host key.
debug1: Found key in /Users/****/.ssh/known_hosts:25
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /Users/****/.ssh/id_rsa
debug1: Authentications that can continue: publickey,password
debug1: Trying private key: .vagrant/machines/default/virtualbox/private_key
debug1: Authentication succeeded (publickey).
Authenticated to localhost ([127.0.0.1]:2222).
debug1: Local connections to LOCALHOST:5432 forwarded to remote address localhost:5432
debug1: Local forwarding listening on ::1 port 5432.
debug1: channel 0: new [port listener]
debug1: Local forwarding listening on 127.0.0.1 port 5432.
debug1: channel 1: new [port listener]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
```

**Comment by ChristianVermeulen** [comment]
@psequel funny thing is, if I now try to open is in psequel, all of a sudden it **does** work... Maybe because I had to accept the remote host?

**Comment by psequel** [comment]
I think that's because it asked you to confirm adding your host to known_hosts. Because PSequel is not a terminal, it's unable to ask you to do that. So you need to run it in terminal for the first time, confirm adding your host, and you can connect to it with PSequel from then on.
