### ISSUE TITLE
Can't save a query bookmark

### ISSUE THREAD

**Issue by washburnad** [psequel/psequel#130]
Thanks for the great tool.  I use it daily.
However, I can't use the bookmarks as I can't save.  I'm on Mac OS X Yosemite useing PSequel 1.5.0.  The suggestion is to right-click to create a new bookmark.  I have tried long-click, cmd-click, option-click, ctrl-click and various combinations with no luck.  What is the Mac method to save a bookmark?

**Comment by psequel** [comment]
Yes, just right click on the empty area or on a folder name. With a touchpad, click with two fingers or control-click is the equivalent of right click.

**Comment by washburnad** [comment]
Thanks for the quick reply. Enabling the 2 finger click on the touchpad does work (I usually have it disabled), but ctrl-click does not work.
