### ISSUE TITLE
limit row fetches

### ISSUE THREAD

**Issue by santagada** [psequel/psequel#131]
Psequel tries to select whole tables to show on the ui, paginate results and get only part of them or else for big databases its unusable.

**Comment by psequel** [comment]
At the bottom right of the content view, there is a "Gear" button. Click on it and change the page size there.

**Comment by santagada** [comment]
Just tried it was sorting that was killing psequel on my tables, strange that other tools were working just fine (SQL Workbench/J and DataGrip). Postico was having the same problem (it also tries to sort by primary key as well.
