### ISSUE TITLE
SIGILL Crash on OS X 10.10.1

### ISSUE THREAD

**Issue by matheus2740** [psequel/psequel#133]
Upon trying to connect to a database, PSequel crashes with BAD INSTRUCTION (SIGLL). I believe this to be because I have an older computer, with first gen i5 (m430 Arrendale) processor, and the compiler must be spitting some instruction which is not supported on my processor.

The offending instruction is:
```
* thread #1: tid = 0x71fa, 0x0000000109b3089a psqlodbcw.so`initialize_global_cs + 35, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x0000000109b3089a psqlodbcw.so`initialize_global_cs + 35
psqlodbcw.so`initialize_global_cs:
    ->  0x109b3089a <+35>: vxorps %ymm0, %ymm0, %ymm0
```
Which turns out to be an AVX extension (not supported on Arrendale).

I Believe this to be solvable by compiling PSequel with -O0, which shouldnt vectorize anything.
Could you please make a build with no optimizations?

It would be very useful for people with older macs.

**Comment by psequel** [comment]
Try [this](https://github.com/psequel/psequel/issues/106#issuecomment-246459586) to compile psqlodbc yourself.

**Comment by matheus2740** [comment]
Thanks, this fixed it for me.
