### ISSUE TITLE
Unable to connect through SSH tunnel

### ISSUE THREAD

**Issue by ace** [psequel/psequel#136]
Hi.

I'm trying to connect to a remote PG using SSH Tunneling, but I get several dialogs asking for the remote user SSH password. It seems something related to the SSH key passphrase, according to the window log I get after the failed attempt. This is the relevant portion:

```
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /path_to_my_key
debug1: Server accepts key: pkalg ssh-rsa blen 535
debug1: read_passphrase: can't open /dev/tty: Device not configured
```

I have the passphrase in Keychain, ssh-agent running and ssh-add -l shows it.

I've also tried to run the port forwarding command in a terminal, as you suggested in #128. There, it connects, nothing is asked for:

```
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /path_to_my_key
debug1: Server accepts key: pkalg ssh-rsa blen 535
debug1: Authentication succeeded (publickey).
```

**Comment by psequel** [comment]
Which version of PSequel are you using?

**Comment by ace** [comment]
I'm using 1.5.1.

**Comment by psequel** [comment]
Did you install a third-party version of ssh? What's the output of `which ssh` and `which ssh-add`?

**Comment by ace** [comment]
They are both from `/usr/bin`, no third-party version.

```
→ which ssh
/usr/bin/ssh

→ which ssh-add
/usr/bin/ssh-add
```

**Comment by psequel** [comment]
Please try v1.5.2

**Comment by ace** [comment]
It works, connecting without problem. Thanks!
