### ISSUE TITLE
How can I move bookmarks to new computer?

### ISSUE THREAD

**Issue by jayshepherd** [psequel/psequel#138]
I need to move all my bookmarks to another installation on another computer. Is there a way to access the text? or do I need to open each of them and copy/paste on the new installation.

**Comment by psequel** [comment]
All application data (connections, bookmarks, query history, etc) are stored inside `~/Library/Application Support/com.psequel.PSequel/`.

**Comment by jayshepherd** [comment]
That worked perfectly.  Thanks.
