### ISSUE TITLE
CMD+R text selection awareness

### ISSUE THREAD

**Issue by bwiggs** [psequel/psequel#14]
Wouldn't it be cool if in the query view, CMD+R would check to see if there was any highlighted text and use that as the text to run as the query instead of all the text in the query window. Then you could highlight little snippets within the query editor and run them individually.

**Comment by PeterDP** [comment]
I second this new feature request as well. It would be a real boon to the work flow.

**Comment by jayshepherd** [comment]
+1

This is a huge workflow benefit. In many other editors, I typically have multiple queries that I'm working through and can just highlight and run.

**Comment by ankushg** [comment]
+1

**Comment by tsmeyer** [comment]
+1  
when doing complex nested selects, being able to highlight and run the inner queries is a huge help.

**Comment by Matejkys** [comment]
+1

**Comment by psequel** [comment]
Implemented in v1.3.0

**Comment by jayshepherd** [comment]
Just tried it out. Thank you very much! This is a huge feature for me and I'm sure others as well.

**Comment by bwiggs** [comment]
Sweet! Thanks!
