### ISSUE TITLE
Disable auto-capitalization of keywords in function definitions

### ISSUE THREAD

**Issue by psylum** [psequel/psequel#140]
If you are using the query editor and are trying to create a function using a language extension (such as `plpythonu`), the auto-capitalization causes the code contained in the function body to become invalid.

PSequel Version: 1.5.2
macOS Version: 10.11.6
PostgreSQL Version: 9.6.0

Instructions:
Paste an extension's function definition into the query editor.

Expected Behavior:
The function 'source' remains unchanged and can be run.

Actual Behavior:
Keywords such as `return`, `if`, etc. are capitalized, rendering them invalid in the language being executed.

Example Inputs:
https://www.postgresql.org/docs/current/static/plpython-data.html
pymax (44.3.2): causes `ERROR: could not compile PL/Python function "pymax"`
multiout_simple_setof (end of page) causes `ERROR: NameError: global name 'RETURN' is not defined`

**Comment by psequel** [comment]
You could disable auto-capitalization altogether.

**Comment by psylum** [comment]
is there a preference for that? I looked for something in the edit menu but didn't see anything that appeared to be PSequel specific re: sql keywords.

**Comment by psequel** [comment]
Click the "gear" button under the query editor.

**Comment by psylum** [comment]
Totally missed that. thanks!
