### ISSUE TITLE
ctrl+c for easier copy

### ISSUE THREAD

**Issue by rdp** [psequel/psequel#143]
Would be nice if highlighting "some data" for instance in a "content" pane, then command+c would copy it as CSV, today command+c seems to do nothing.  So I guess remap some key bindings the current one is a bit confusing.

Cheers!

**Comment by jayshepherd** [comment]
I agree that this would be helpful. I do this instinctively and have always wished it would copy something. Maybe cmd+c for cell, and cmd+shift or option c for row(s)

**Comment by rdp** [comment]
Yeah, I think what people typically expect is for cmd+c to copy "whatever all is currently highlighted" so that'd be my vote for default anyway :)
Cheers!

**Comment by psequel** [comment]
In v1.5.3, you could press ⌘C to copy selected rows as CSV, without headers

**Comment by rdp** [comment]
thanks!

**Comment by brunolemos** [comment]
This should work on every row in the app (e.g. Structure), not only Content rows.
