### ISSUE TITLE
Search for available databases on server

### ISSUE THREAD

**Issue by mattcoll** [psequel/psequel#144]
I am a new to front-end development and don't do much back-end development.
But I would like to be able to search the server for all databases available rather than having to know which one I want straight away. 
Not sure how this would work, but feel it would be a useful addition for some people.
Really like what you have done so far though, keep working on it.

**Comment by Dieken** [comment]
Both #144 and #146 were closed...

I also want this feature, this is TablePlus(I'm not its author :-), it's very annoying to create multiple connections for each PostgreSQL catalog(aka. database).

![image](https://user-images.githubusercontent.com/2365/30193906-a1ebd8a8-9482-11e7-86e2-2b937a53206a.png)

**Comment by Dieken** [comment]
well...
