### ISSUE TITLE
When selecting tables from the sidebar, PSequel loads all records without paging

### ISSUE THREAD

**Issue by jakeonrails** [psequel/psequel#145]
Regardless of which tab i'm on - Structure / Content / Query, it seems like the app is doing a `select *` query to load all records. This is not good for a table with millions of rows. One table in my app with 70k records ends up taking about 10s to finish when I simply click on it in the sidebar.

When I hit some other tables with more records, PSequel just can't handle it. A minute of beachballing and then the app crashes.

Could you make it so the query paginates? Or so that you only load all records when you're on the Content tab instead of Structure or Query? My 99.9% use case for clicking the sidebar at all is to get structure info anyways.

**Comment by psequel** [comment]
Query results are paginated by default, unless you set the page size to be "unlimited" (via the gear button at the bottom right of the Content tab).

**Comment by jakeonrails** [comment]
Ah! I must have changed that when I first started using PSequel, not knowing that it was a permanent setting, and then I've avoided the content tab ever since so I never saw it again. Thank you!

**Comment by psequel** [comment]
In v1.5.3, the "unlimited" is replaced with "10000" to avoid situations like this. After all, if you have 10000+ records in a table, it doesn't make much sense to see them all at once.
