### ISSUE TITLE
open multiple connections

### ISSUE THREAD

**Issue by dingb** [psequel/psequel#149]
It would be good to be able to open multiple connections like Sequel Pro for MySql, for now if I want to connect to another db, I have to quit existing one and open a new one for the new db connection. Is there anything I am missing here? Or the functionality may has been provided, but I just didn't find it? Thanks. It is a great tool.

**Comment by psequel** [comment]
cmd + N to open a new window, as you would do for many other macOS apps.

**Comment by dingb** [comment]
Cool, thanks, good enough, if it can be done by cmd + t in the same window, that would be perfect.

**Comment by psequel** [comment]
If you are on macOS Sierra, Tabs feature is supported by the OS. See [this](http://www.macworld.com/article/3088342).
