### ISSUE TITLE
sync connections between computers

### ISSUE THREAD

**Issue by joseramonc** [psequel/psequel#153]

**Comment by psequel** [comment]
You could just copy `~/Library/Application Support/com.psequel.PSequel` to the other computer, although this will copy your query history, bookmarks, etc too, not just connections.

**Comment by joseramonc** [comment]
It would be great if it could be done via iCloud or something more automatic, so that I don't get to change that file every time I add a new connection on a computer. 

But this is fine for now, thanks for your great app 😄
