### ISSUE TITLE
Ability to enter SSH password for SSH connections

### ISSUE THREAD

**Issue by michaelperrin** [psequel/psequel#17]
SSH tunneling has been a great addition to PSequel last month!

But it is not always possible to connect to a server using SSH tunneling when the key needs a password.
In that case, the message _fe_sendauth: no password supplied_ appears when connecting.

It would be necessary to add a fifth field to the _SSH_ tab for connection, to enter the password associated to the Identity File, or the user should be prompted to enter his password.

**Comment by silverki** [comment]
Yes. That will be appreciated. Ad-hoc fix is to establish tunnel with os X ssh client.
`ssh -i identity_file -L 5432:localhost:5432 sshuser@sshhost`

**Comment by psequel** [comment]
Since using password instead of private key to connect to a host is unsecured, this feature is low priority one. The most appropriate fix for this issue is to have your admin fix the ssh host config.

**Comment by michaelperrin** [comment]
Hi @psequel , thanks for your answer. But I think there's a little misunderstanding. I'm talking about a password on the private key, not a password to connect to SSH.
You know, when you generate your key with the `ssh-keygen` command, you are asked for an optional password for the key, this is the password I am talking about here.

So this is even more secure than just using the private key.

**Comment by psequel** [comment]
The `ssh` program doesn't support passing a passphrase as an argument - it always prompts for the passphrase. This makes it a little complicated to implement your suggested feature. An easy solution on your side is to [add that SSH key passphrase in Keychain manually](https://help.github.com/articles/working-with-ssh-key-passphrases/#os-x-keychain).

**Comment by riula** [comment]
Hi @psequel ! Having the ability to use a password would be great when working locally with vagrant / docker / virtual machines. Its less secure, sure but it makes things much easier when the entire environment is confined to your computer. Perhaps an optional to use either or, similar to pgAdmin3? Anyways, keep up the great work!

**Comment by psequel** [comment]
Hi @riula, you misunderstood the problem this post is talking about. See @michaelperrin's comment above. BTW, I don't agree with you. Using a password instead of a private key doesn't make things easier. If you have control over your environment, why not just `ssh-keygen`?

**Comment by riula** [comment]
Hey @psequel thanks for the response! I see now that I misunderstood the post, however, my stance remains on allowing for simplicity. I am working on a project that has a server configured using ansible (the server and playbook were setup entirely by the client), and it is set up to use passwords at the moment. In other words, I don't have control over the system - my hands are tied. I've been given the playbook to set up a local environment, so for local development psequel is doing the trick, but the lack of flexibility means I'm back to pgAdmin3 for the staging server. I understand the idea of not letting people shoot themselves in the foot by ensuring secure practices, but flexibility is a nice thing. 
Thanks again!

**Comment by psequel** [comment]
@riula I understand that. But this would be a low priority feature. In the meantime, if you do want to use PSequel, you could simply have an SSH tunneling session running in terminal.

**Comment by Brade** [comment]
Uh oh, another hyper-opinionated developer refusing to implement a basic useful feature =(

Yes, a password field would be hella convenient for vagrant setups. Why not let us worry about our own security concerns? Plus the "identify file" selection field doesn't seem to work anyway. I try to pick the one that vagrant uses by default, but the error box seems to indicate that it's still checking ~/.ssh/id_rsa regardless.

**Comment by psequel** [comment]
@Brade If you think the "identify file" is not working, please create a separate issue. Please include your PSequel and OS X versions in that issue.

**Comment by mdular** [comment]
:+1: 

I would agree with the security argument, however in a multi-project (and thus, multi-vagrant) environment, connecting just with vagrant / vagrant is nice - and security not a concern in that scenario

It's still only a 'nice to have', because it can be worked around by ssh-add'ing the key, but please consider that the priority should not be based on the security argument alone, as it simply doesn't always apply.

Great tool thus far! Glad to see a sequelPro inspired pgsql GUI in the works :)

**Comment by keeprock** [comment]
I'm stumbled on this too. Common case scenario is Vagrant setup. It's just don't work out of the box with default id_rsa. For development use case it is easier to just type password.

**Comment by psequel** [comment]
Implemented in v1.5.1.
