### ISSUE TITLE
Download link is broken

### ISSUE THREAD

**Issue by jacobfogg** [psequel/psequel#174]
Currently, I get an error message from Dropbox that the link is no longer valid. I tried every version from your previous version list and they are all broken.

**Comment by brianmwadime** [comment]
Happened to me as well.

**Comment by mjhanda** [comment]
The file doesn't exist or is permissioned off from public.

**Comment by brianmwadime** [comment]
@mjhanda yes, basically we're inquiring on whether  @psequel will fix this?

**Comment by mjhanda** [comment]
I opted for pgAdmin in the interim.

**Comment by psequel** [comment]
I'm so sorry, everyone! I accidently turned on Dropbox sync on a new computer and didn't notice that all my files were gone! I've restored them. The download link should work now. Thanks for letting me know!
