### ISSUE TITLE
query table or column name always converted to lower-case

### ISSUE THREAD

**Issue by toshim45** [psequel/psequel#208]
I have table and column name which contain upper case letter (I can't change this because this is other team domain).

I use PSequel v 1.5.3

case 1: upper case letter on table
For example: `table Tenant`
my query: `SELECT id,code FROM Tenant;`
always got error: `relation "tenant" does not exist` -> seems its converted to lower-case

<img width="797" alt="Screen Shot 2020-03-09 at 11 21 37 AM" src="https://user-images.githubusercontent.com/8453594/76183355-b3886480-61fa-11ea-8a27-6e824d14553d.png">

case 2: upper case letter on column
For example: `table TenantConfig` it has column `tenantId`
I open tab `Content` and then put `tenantId='something'` on WHERE filter,
also got ERROR: column "tenantid" does not exist -> seems converted to lower-case 

<img width="798" alt="Screen Shot 2020-03-09 at 11 40 18 AM" src="https://user-images.githubusercontent.com/8453594/76183396-ce5ad900-61fa-11ea-87e6-6604d1a4e69e.png">

could you pls checking this ? 
thanks a lot

**Comment by matheusalxds** [comment]
I got the same problem. It seems the PSequel accepts only lowercase. =/

**Comment by matheusalxds** [comment]
I found a way to solve this problem, you can write the word in double quotes:
`"isWorking"=true`.

**Comment by toshim45** [comment]
nice @matheusalxds thanks for the workaround

```
"tenantId"='008132BC-5DC4-4DF7-ABAE-875F10AAACE2'
```
works for me
