### ISSUE TITLE
Show Views in table list

### ISSUE THREAD

**Issue by bwiggs** [psequel/psequel#23]
It would be nice to be able to see the views along with the tables.

**Comment by amanpatel** [comment]
:+1:

A ton of use for this tool is to browse data, and views are a big part of it.

**Comment by M4urice** [comment]
:+1:

**Comment by davidkuep** [comment]
Definitely agree!!

**Comment by Prizephitah** [comment]
+1 Along with the possibility to refresh materialized views.

**Comment by psequel** [comment]
Implemented in v1.3.4.

**Comment by bwiggs** [comment]
Works for me! Thanks @psequel

**Comment by kevkon3** [comment]
@psequel I'm wondering if this got removed with the latest version? I'm using 1.5.3 and I am not seeing my materialized views anymore. This was previously working for me with 1.5.2.
