### ISSUE TITLE
"freeze" when viewing large tables

### ISSUE THREAD

**Issue by rdp** [psequel/psequel#66]
Beach ball for "large" tables:

How to reproduce:

create a table with 1B rows or some other large  number.

select it in PSequel.

It seems to just beach ball forever.  Perhaps it's trying to do a very long "count" to determine the table size (Postgres is slow with counts sometimes it seems).  If this ends up being the problem perhaps could use "estimated table size" instead for large tables. Cheers!

**Comment by psequel** [comment]
Did you set the page size to be unlimited? PSequel already uses "estimated table size" for large tables.

**Comment by rdp** [comment]
Interesting.  I did have it set to unlimited, but changing it back to "10" and it still seems to have the "forever" wait time.  running "select * from pg_stat_activity" seems to reveal these type of queries are being performed:

SELECT COUNT(*) FROM "x"."y"

I have seem it say "~ 1000" before for the row count, but now it appears to be using only (and always) precise values, maybe I tained my local install with my playing around with it (?)

**Comment by psequel** [comment]
PSequel uses `SELECT reltuples FROM pg_class WHERE oid = 'x.y'::regclass" to get an estimated row count. If the returned value is less than 10k, it will then use `SELECT COUNT(*) FROM "x"."y"` to get an accurate count. That's why you saw "~ 1000" initially before it's replaced with an accurate count.

I don't think querying the row count is the issue here. You could confirm this by turning off row counts in Preferences. How large is each row in your table? Is there a blob or binary column in that table which stores huge amount of data?

**Comment by rdp** [comment]
Interesting.
If I uncheck both then it "works fine" (shows data, but shows no row counts
obviously).
With "order by primary key" checked (and "show table row counts" unchecked)
it also still works great.

With "Show table row counts" checked it fails (beach ball).

One interesting thing to mention:
in this particular case I actually have more than 4B rows in that table, if
that makes any kind of "overflow" type...

Cheers!

**Comment by psequel** [comment]
I guess somehow your `relstuples` table isn't getting updated so PSequel thinks your `y` table has only ~1000 rows.

**Comment by rdp** [comment]
That is indeed odd.
If I run this
SELECT reltuples FROM pg_class WHERE oid = 'streamreftotape'::regclass;
I get this response:

1.1895937

(very odd, considering it has 4B plus rows).
Starting to sound like a postgres bug/overflow issue...

**Comment by rdp** [comment]
OK doing some more study, I saw somebody do a different query
http://stackoverflow.com/a/14570679/32453
:

SELECT reltuples::BIGINT AS estimate FROM pg_class WHERE
relname='schema_name.tbl';


and this one returns "a right" value, in this case 11B
11895937024
instead of that weirdly truncated one. Weird.

**Comment by psequel** [comment]
Thanks for your help with investigating this issue! It has been fixed in v1.2.7.
