### ISSUE TITLE
Crashes when opening a table in El Capitan

### ISSUE THREAD

**Issue by eamon-hguk** [psequel/psequel#70]
Version 1.2.7 crashes when opening a table.
1.2.6 does not have this problem

**Comment by tanrax** [comment]
Exactly, I have the same problem

**Comment by fedeonline** [comment]
me too

**Comment by rfjakob** [comment]
Me as well. It crashes with `Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)`.
Backtrace: https://gist.github.com/rfjakob/dd091492692297385d5e

**Comment by kenips** [comment]
:+1:

**Comment by christianklotz** [comment]
+1

**Comment by dsappana** [comment]
+1

**Comment by psequel** [comment]
Sorry I forgot to test it on El Capitan as I'm still using Yosemite for development. I hate that Apple keeps changing things. Working on a fix now.

**Comment by tanrax** [comment]
Thanks for the effort :)

**Comment by mbablok** [comment]
Thank you for working on the program, I find it very useful and handy.

**Comment by m0n9oose** [comment]
+1

Thanks a lot

**Comment by davidpaulhunt** [comment]
Same problem.

+1 for working on it

Luckily, the query interface still works!

**Comment by psequel** [comment]
Fixed in v1.3.0

**Comment by eamon-hguk** [comment]
Thank you very much, great application!

**Comment by tanrax** [comment]
Fabulous ! Good job 

Have you considered include brew ?

**Comment by christianklotz** [comment]
Thank you!

**Comment by psequel** [comment]
@tanrax did you mean brew cask? I don't use it personally but could you help maintaining the formula for PSequel?

**Comment by tanrax** [comment]
@psequel It is easier than you think. They are only two commands. 

https://github.com/Homebrew/homebrew/tree/master/share/doc/homebrew#readme

Look section : 
Contributing

**Comment by psequel** [comment]
@tanrax what you're talking about is homebrew, not homebrew-cask. Homebrew is for CLI tools and libraries only. [PSequel is in homebrew-cask already.](https://github.com/caskroom/homebrew-cask/blob/master/Casks/psequel.rb)
