### ISSUE TITLE
ERROR: Unsupported startup parameter: geqo

### ISSUE THREAD

**Issue by warik** [psequel/psequel#71]
Yes, I'm using pgbouncer in front of my postgres instances.

**Comment by psequel** [comment]
I'm not familiar with pgbouncer. What's that "gepo" parameter for? Could you add it into `ignore_startup_parameters`?

**Comment by warik** [comment]
I also have no idea what this parameter is about. Adding it to pgbouncer igrnore_parameters helped, but I don't its good solution in general.

**Comment by rdp** [comment]
I get this too, unfortunately.  Can't cannot to any of my databases now (they all use pgbouncer)? (1.3.0)

**Comment by psequel** [comment]
Do you get this error when PSequel is trying to connect to your database, or when it's trying to run a query?

**Comment by psequel** [comment]
OK, I just did some research on "geqo". My understanding is that, [GEQO is a query optimizer used by PostgreSQL server](http://www.postgresql.org/docs/9.4/static/runtime-config-query.html#RUNTIME-CONFIG-QUERY-GEQO) and [it should be added into PgBouncer's `ignore_startup_parameters`](https://pgbouncer.github.io/config.html#ignorestartupparameters).

**Comment by rdp** [comment]
It's when trying to connect to the database.  PgAdmin is able to connect (to pgbouncer) without throwing an exception.  unfortunately I don't really "control" the database's (nor pgbouncer's parameters) in this case... (older versions of psequel didn't have this problem FWIW)

**Comment by psequel** [comment]
That's because older version of PSequel uses a newer but less stable version of driver. Unfortunately that driver crashes PSequel for some users (although I'm unable to reproduce the crash myself). Let me see if I can patch the driver.

**Comment by rdp** [comment]
1.4.2 seems to not fail anymore for me, FWIW. thanks!

**Comment by Haimirick** [comment]
Try to set  SSL Mode=Require; in connection String
