### ISSUE TITLE
Refresh materialized view

### ISSUE THREAD

**Issue by Prizephitah** [psequel/psequel#77]
It would be nice if materialized views had the context menu option to refresh the view. It would really simplify that task.

**Comment by psequel** [comment]
Just hit cmd + R to refresh - it reruns the query effectively.

**Comment by Prizephitah** [comment]
Oh, that is handy but maybe a wee bit hidden. I think that an explicit option would be nice to have.

**Comment by psequel** [comment]
If you click the arrow next to the "Run All Queries" button, you can see its shortcut.

**Comment by Prizephitah** [comment]
I knew about the shortcut, but I meant that it wasn't obvious to me that running the query would refresh the materialized view.
