### ISSUE TITLE
Set the search_path to the selected schema

### ISSUE THREAD

**Issue by Prizephitah** [psequel/psequel#78]
It would simplify writing queries if the search_path was set to the currently selected schema. Perhaps the path should be set to `<schema>,public` or maybe it should be an option in the preferences dialog.

**Comment by psequel** [comment]
That's a great idea! Will be available in the next release.

**Comment by Prizephitah** [comment]
👍

**Comment by psequel** [comment]
Implemented in v1.3.5.
