### ISSUE TITLE
Refresh Tables Hot Key

### ISSUE THREAD

**Issue by bwiggs** [psequel/psequel#80]
Working on some database changes and I keep needing to click the refresh tables button. Would be great if I could do that via hotkey. `CMD+SHIFT+R` ?

**Comment by psequel** [comment]
There is already a hotkey for that. It's cmd+R. Pro tip: move your mouse over a button to see its shortcut, if it has one.

**Comment by psequel** [comment]
Implemented in v1.3.5.

**Comment by bwiggs** [comment]
Terrific! Thank you!
