### ISSUE TITLE
Multiple queries returned in query view

### ISSUE THREAD

**Issue by bwiggs** [psequel/psequel#82]
Just saw this when using the cmd+r hotkey. If I tap it once I see the query is run once. However if I hold it down, the query gets run multiple times very rapidly, and __the results stack up in the query results view__.

Note: I do have my mac key repeat tuned way down. 

```
defaults write NSGlobalDomain KeyRepeat -int 0
```

![psequel-results-piling-up](https://cloud.githubusercontent.com/assets/7358/11255133/2d360a90-8e0a-11e5-8e80-96f65b06cc1d.gif)

**Comment by psequel** [comment]
I think that's expected. Holding cmd+R is like pressing cmd+R multiple time. Try holding cmd+R in your web browser and you will notice similar behavior.

**Comment by bwiggs** [comment]
The query is only supposed to return a single column. It looks like queries are stacking up and rendering in a single view.

**Comment by psequel** [comment]
Fixed in v1.3.5.

**Comment by bwiggs** [comment]
excellent!
