### ISSUE TITLE
Show name of current database in title, window list

### ISSUE THREAD

**Issue by houshuang** [psequel/psequel#84]
Related to #83, I now have three windows open with three different databases on the same server (each database represents a course, the internal structure is identical, so I am running the same query on all three). However, all are called "new connection" in the window list, and there is no indication of which window belongs to which course.

**Comment by psequel** [comment]
Then you should rename your connections to something other than ""new connection"

**Comment by houshuang** [comment]
Yes, I could do that, or you could take the information that you already
have and display that.

On Wed, Nov 25, 2015 at 12:04 AM, PSequel <notifications@github.com> wrote:

> Then you should rename your connections to something other than ""new
> connection"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/psequel/psequel/issues/84#issuecomment-159492881>.
>



-- 
http://reganmian.net/blog -- Random Stuff that Matters

**Comment by psequel** [comment]
Implemented
