### ISSUE TITLE
"Run current query" shortcuts are broken

### ISSUE THREAD

**Issue by torra** [psequel/psequel#86]
When I am in the Query pane, I am unable to get either of the two "run" keyboard shortcuts to work.

I have two simple queries there - one populates a table, and the other selects from it. The UI indicates that the shortcut to "Run all queries" is CMD + R - rather, this seems to run only the first query in the pane. The other option is "Run current query", and the shortcut indicated is CMD + OPT + R - all this seems to do is move context from the Query pane to the Content pane.

Also (perhaps another issue entirely) - if I try to "Run all queries" with two in the pane, it seems to hang after the first query and the loading indicator does not change. The "Run current query" button (not the shortcut) works as expected.

**Comment by psequel** [comment]
The shortcut is fixed in v1.4.0. "Run all queries" functionality has been removed.
