### ISSUE TITLE
Remember SSH key used for SSH Tunneling

### ISSUE THREAD

**Issue by kyle-mccarthy** [psequel/psequel#99]
I use vagrant so the Identity File/SSH key always stays the same.  It should remember the location of they key if the connection to the server is successful.

**Comment by psequel** [comment]
I think PSequel does remember the Identity File field. What do you mean by "SSH key"? And which version of PSequel are you using?

**Comment by kyle-mccarthy** [comment]
I am currently using v1.4.2, but the Identity File field does not get remembered.  When I was saying "SSH Key" I was incorrectly referring to the Identity File field.

**Comment by psequel** [comment]
I'm unable to reproduce this bug. Let's wait a while to see if others are reporting the same issue.

**Comment by psequel** [comment]
Fixed in v1.4.3. Credit to [this comment](https://github.com/psequel/psequel/issues/7#issuecomment-172818095).
